### PR TITLE
Switch back to original asynctools

### PR DESCRIPTION
**Pull request by pigmej**
This was merged: https://github.com/cheatfate/asynctools/pull/18 so it's safe to switch back to original asynctools

### CODE REVIEW

**Comment by dom96** [comment]
Tests are failing though :/

**Comment by pigmej** [comment]
That's a werid one, the code is 1:1 the same for original and forked one after cheatfate/asynctools#18 was merged.

**Comment by pigmej** [comment]
@dom96 the same error is happening on `master` branch. Is this 0.20 thingy?

**Comment by dom96** [comment]
I guess we'll need another PR to fix it in asynctools?

**Comment by dom96** [comment]
This is done

**Pull request closed without merging**
